### ISSUE TITLE
Y.CMS 2.0  1.9.3 Undefined index: version

### ISSUE THREAD

**Issue by IvanLadygin** [yoomoney/yandex-money-ycms-opencart3#88]
Notice: Undefined index: version in admin/controller/extension/payment/yandex_money.php on line 1689
Что, в принципе, логично так как модель возвращает пустой массив из 
admin/model/extension/payment/yandex_money.php line 636

не критично, конечно, но и поправить же не трудно....

**Comment by ostulov** [comment]
Добрый день!

Данные предупреждения связаны с переездом репозитория для хранения установочного кода модуля. Когда переезд завершится, предупреждения будут исправлены. 
На текущий момент они не влияют на функциональность модуля, и Вы можете их проигнорировать.
