### ISSUE TITLE
ЮMoney

### ISSUE THREAD

**Issue by webair-studio** [yoomoney/yandex-money-ycms-opencart3#91]
Будет ли пока работать старый редирект на url страницу оплаты? Вопрос про способ оплаты через Яндекс Деньги, а не Яндекс Касса.
То есть, будет ли пока поддерживаться старый url перехода к оплате?

**Comment by ostulov** [comment]
Добрый день!

Да, старый адрес для отправки запросов будет доступен на время, необходимое для переезда на новый адрес. О закрытии поддержки старых адресов мы оповестим.
